#!/usr/bin/env node

var es6Detective = require('detective-es6');
var amdetective = require('amdetective');
var glob = require('glob');
var fs = require('fs');
var _ = require('lodash');

var root = _.last(process.argv),
    format = process.argv[process.argv.indexOf('-f') + 1] || 'es6';

glob(root + '**/*.js', function (err, files) {
    var data = [];

    files.forEach(function (fileName) {
        var mySourceCode = fs.readFileSync(fileName, 'utf8'),
            dependencies = [];

        if (format === 'es6') {
            dependencies = es6Detective(mySourceCode);
        }

        if (format === 'amd') {
            dependencies = amdetective(mySourceCode);
            console.log(dependencies);
        }

        data.push({
            name: clean(fileName),
            imports: dependencies.map(clean)
        });
    });

    process.stdout.write(JSON.stringify(data, null, 4));
});

function clean (f) {
    return f
        .replace('.js', '')
        .substr(f.lastIndexOf('/') + 1);
}


